all:
	g++ Q1-1_brute_force_knapsack.cpp -o Q1-1_brute_force_knapsack.out
	g++ Q1-2_greedy_algorithm.cpp -o Q1-2_greedy_algorithm.out
	g++ Q1-3_dynamic_programming_knapsack.cpp -o Q1-3_dynamic_programming_knapsack.out
	g++ Q2_dijikstra.cpp -o Q2_dijikstra.out
